# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJHvcMh_EOfde4bpELgNJZ4y6trFVoEF
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/movies.csv')
df

# List the top 5 movies with the highest IMDb rating.
df.sort_values('rating',ascending = False)['title'].head(5)

# Find the total number of movies released each year.
df.groupby(by = 'release_year')['title'].count()

# Which genre has the highest average rating?
df2 = df.groupby(by = 'genre')['rating'].mean().sort_values(ascending = False)
df2.head(1)

# Find the movie(s) directed by "Christopher Nolan".
df[df['director'] == 'Christopher Nolan']['title']

# What is the average duration of movies released after 2010?
df3=df[df['release_year']>2010]
df3['duration'].mean()

df

# List all movies with a revenue greater than $500 million.
df[df['revenue_millions']>500]['title']

# Find the number of movies for each genre.
df.groupby('genre')['title'].count()

# Which year had the highest number of movie releases?
df.groupby('release_year')['title'].count().sort_values(ascending = False).head(1)

# List the top 3 directors who have directed the most movies.
df.groupby('director')['title'].count().sort_values(ascending = False).head(3)

# Find all movies where the duration is above the average duration.
average = df['duration'].mean()
df[df['duration']>average]['title']

